/* Vision Sports Live Proof — verifies visible body movement only. */
(function(){
'use strict';
var CFG=window.SUPABASE_CONFIG||{},FN=(CFG.url?CFG.url.replace(/\/$/,''):'')+'/functions/v1/',ANON=CFG.anonKey||'';
var $=function(id){return document.getElementById(id);};
var stages=['introStage','revealStage','camStage','doneStage'];
function show(id){stages.forEach(function(s){var e=$(s);if(e)e.classList.toggle('on',s===id);});}
var S={invite:null,sport:'all',previous:null,task:null,token:null,sessionId:null,stream:null,coach:null,seq:0,startedAt:0,finishing:false,last:null,trackingLoss:0,lastTracking:null,fps:0,lastFrame:0,latency:[]};
function api(path,body){return fetch(FN+path,{method:'POST',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON},body:JSON.stringify(body||{})}).then(function(r){return r.json().then(function(j){return{ok:r.ok,data:j};});});}
function device(){var ua=navigator.userAgent||'';return{browser:/CriOS|Chrome\//.test(ua)?'Chrome':/Safari\//.test(ua)?'Safari':/Firefox\//.test(ua)?'Firefox':'unknown',os:/iPhone|iPad/.test(ua)?'iOS':/Android/.test(ua)?'Android':/Mac/.test(ua)?'macOS':/Windows/.test(ua)?'Windows':'unknown',device:/Mobi|Android|iPhone/.test(ua)?'mobile':'desktop',user_agent:ua.slice(0,400)};}
function stop(){try{if(S.coach&&S.coach.stop)S.coach.stop();}catch(e){}try{if(S.stream)S.stream.getTracks().forEach(function(t){t.stop();});}catch(e){}S.stream=null;S.coach=null;}
function getCamera(){return navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:30}},audio:false}).then(function(stream){S.stream=stream;var v=$('cam');v.srcObject=stream;return v.play().then(function(){return stream;});});}
function baseVerifierTitle(task){if(task.verifier_id==='v3-soccer')return'Soccer Drill';if(task.verifier_id==='v3-shadowboxing')return'Shadowboxing';return'Verified Movement';}
function redeem(){return api('beta-live-start',{invite_token:S.invite,environment:'sports',sport:S.sport,previous_exercise:S.previous,device:device()}).then(function(r){if(!r.ok||!r.data||!r.data.session_id)throw new Error(r.data&&r.data.error||'assignment_failed');S.task=r.data;S.token=r.data.session_token;S.sessionId=r.data.session_id;S.previous=r.data.exercise;return r.data;});}
function renderTask(t){$('taskSport').textContent=(t.sport||'multi sport').replace(/_/g,' ');$('taskTitle').textContent=t.title;var cp=t.camera_profile||{};$('taskSetup').textContent=cp.setup||'Keep your full movement visible.';$('taskClaim').textContent=t.claim_scope==='body_movement_only'?'Vision will verify your visible body movement only — not ball, equipment, score or contact outcomes.':'Vision will verify this movement live.';$('beginBtn').disabled=false;}
function sendEvent(type,payload){if(!S.token)return;api('beta-live-event',{session_token:S.token,seq:++S.seq,t_ms:S.startedAt?performance.now()-S.startedAt:0,type:type,payload:payload||{}}).catch(function(){});}
function progress(state){var target=(S.task&&S.task.target_value)||25;var ms=state.clientClaimedDurationMs||state.validDurationMs||0;return{seconds:Math.round(ms/1000),target:target,frac:Math.min(1,ms/(target*1000))};}
function confidence(state){var v3=state.v3&&state.v3.result;var vis=v3&&v3.requiredLandmarksVisible!=null?v3.requiredLandmarksVisible:(state.trackingConfidence||0);return Math.max(0,Math.min(1,.5*(state.trackingConfidence||0)+.5*vis));}
function onUpdate(state){S.last=state;var now=performance.now();if(S.lastFrame){var dt=now-S.lastFrame;if(dt>0)S.fps=S.fps?S.fps*.85+(1000/dt)*.15:1000/dt;}S.lastFrame=now;if(state.poseMs!=null){S.latency.push(state.poseMs);if(S.latency.length>180)S.latency.shift();}if(S.lastTracking===true&&!state.poseTracking)S.trackingLoss++;S.lastTracking=!!state.poseTracking;var p=progress(state);$('seconds').textContent=p.seconds;$('goal').textContent='of '+p.target+' seconds';$('status').textContent=state.poseTracking?'Movement locked':(state.visibilityCue||'Get fully in frame');$('cue').textContent=state.poseTracking?((state.v3&&state.v3.result&&state.v3.result.cue)||state.lastCue||'Keep moving with control'):(state.visibilityCue||'Keep your full body visible');if(state.canFinish===true&&state.evidenceSufficient===true)finish('completed',null);}
function run(){S.finishing=false;S.last=null;S.trackingLoss=0;S.lastTracking=null;S.fps=0;S.lastFrame=0;S.latency=[];S.startedAt=performance.now();var coach=window.VISION&&VISION.liveCoach?VISION.liveCoach.create({video:$('cam'),overlay:null,task:{id:S.sessionId,title:baseVerifierTitle(S.task)},onUpdate:onUpdate}):null;if(!coach)throw new Error('engine_unavailable');S.coach=coach;return coach.start().then(function(r){if(!r||r.ok===false)throw new Error(r&&r.error||'verifier_start_failed');sendEvent('sports_session_started',{sport:S.task.sport,exercise:S.task.exercise,drill_family:S.task.drill_family,claim_scope:S.task.claim_scope,target_value:S.task.target_value});});}
function percentile(a,q){if(!a.length)return null;var b=a.slice().sort(function(x,y){return x-y;});return Math.round(b[Math.min(b.length-1,Math.floor(q*b.length))]);}
function finish(status,reason){if(S.finishing)return;S.finishing=true;var state=S.last||{},p=progress(state),conf=confidence(state);try{if(S.coach&&S.coach.stop)S.coach.stop();}catch(e){}var summary={completion_status:status,valid_duration_ms:p.seconds*1000,confidence:+conf.toFixed(3),tracking_loss:S.trackingLoss,fps:S.fps?+S.fps.toFixed(1):null,latency_ms:percentile(S.latency,.5),browser:device().browser,os:device().os,device:device().device,verifier_engine:'live-proof-v3',verifier_id:S.task&&S.task.verifier_id,verifier_version:S.task&&S.task.verifier_version,failure_reason:reason,telemetry:{environment:'sports',sport:S.task&&S.task.sport,exercise:S.task&&S.task.exercise,drill_family:S.task&&S.task.drill_family,claim_scope:'body_movement_only',latency_p95_ms:percentile(S.latency,.95)}};api('beta-live-finish',{session_token:S.token,summary:summary}).catch(function(){}).then(function(){stop();renderDone(status,summary);});}
function renderDone(status,s){var ok=status==='completed';$('doneTitle').textContent=ok?'Movement verified':'Not verified';$('doneText').textContent=ok?'Vision tracked the required body movement for '+S.task.title+'.':'The movement session was not accepted.';$('doneBad').style.display=ok?'none':'block';$('doneBad').textContent=ok?'':'No sports result, score, ball contact or equipment outcome was accepted.';$('doneSeconds').textContent=Math.round((s.valid_duration_ms||0)/1000)+'s';$('doneConfidence').textContent=Math.round((s.confidence||0)*100)+'%';$('doneFps').textContent=s.fps?Math.round(s.fps):'—';$('doneLoss').textContent=s.tracking_loss||0;show('doneStage');}
function assign(){show('revealStage');$('beginBtn').disabled=true;$('taskTitle').textContent='Assigning…';return getCamera().then(redeem).then(renderTask).catch(function(e){stop();$('taskTitle').textContent='Could not start';$('taskSetup').textContent=String(e&&e.message||e);});}
Array.prototype.forEach.call(document.querySelectorAll('.sport'),function(b){b.addEventListener('click',function(){S.sport=b.getAttribute('data-sport')||'all';Array.prototype.forEach.call(document.querySelectorAll('.sport'),function(x){x.classList.toggle('active',x===b);});});});
$('startBtn').addEventListener('click',assign);$('backBtn').addEventListener('click',function(){stop();show('introStage');});$('beginBtn').addEventListener('click',function(){show('camStage');run().catch(function(e){finish('failed',String(e&&e.message||e));});});$('closeBtn').addEventListener('click',function(){finish('cancelled','user_cancelled');});$('nextBtn').addEventListener('click',assign);$('changeBtn').addEventListener('click',function(){show('introStage');});
S.invite=new URLSearchParams(location.search).get('invite');if(!S.invite){$('startBtn').disabled=true;$('startBtn').textContent='Invite required';}
window.addEventListener('pagehide',function(){if(S.token&&!S.finishing)finish('cancelled','page_closed');else stop();});
})();