/* Vision Public Live Proof BETA — Home/Gym tester controller.
   The tester chooses only an environment. The server chooses the exact exercise
   from a qualified pool. The real V3 verifier remains fail-closed and unchanged. */
(function(){
'use strict';
var CFG=window.SUPABASE_CONFIG||{},FN=(CFG.url?CFG.url.replace(/\/$/,''):'')+'/functions/v1/',ANON=CFG.anonKey||'';
var IS_MOBILE=/Mobi|Android|iPhone|iPad|iPod/i.test(navigator.userAgent||'');
var WARMUP_MS=32000,HARD_CAP_MS=180000,BG_MS=20000;
var $=function(id){return document.getElementById(id);};
var stages=['gateStage','browserStage','introStage','revealStage','camStage','doneStage'];
function show(id){stages.forEach(function(s){var e=$(s);if(e)e.classList.toggle('on',s===id);});}
var S={invite:null,environment:null,previousExercise:null,sessionId:null,token:null,task:null,stream:null,facing:'environment',coach:null,seq:0,active:false,warming:false,finishing:false,completed:false,infFps:0,lastInfAt:0,latency:[],camFps:0,camFrames:0,camLast:0,rvfc:null,camTimer:null,trackingLoss:0,lastTracking:null,lastHeartbeat:0,startedAt:0,everReady:false,lastReadyAt:0,lastProgress:0,lastProgressAt:0,bgSince:0,watchdog:null,domVis:{},lastState:null,camQuality:{},ringTarget:0,ringCurrent:0,raf:null};
function device(){var ua=navigator.userAgent||'';var os=/iPhone|iPad|iPod/.test(ua)?'iOS':/Android/.test(ua)?'Android':/Mac OS X/.test(ua)?'macOS':/Windows/.test(ua)?'Windows':/Linux/.test(ua)?'Linux':'unknown';var browser=/Edg\//.test(ua)?'Edge':/OPR\//.test(ua)?'Opera':/CriOS/.test(ua)?'Chrome iOS':/Chrome\//.test(ua)?'Chrome':/Firefox\//.test(ua)?'Firefox':/Safari\//.test(ua)?'Safari':'unknown';var kind=/iPad|Tablet/.test(ua)?'tablet':/Mobi|Android|iPhone/.test(ua)?'mobile':'desktop';return{browser:browser,os:os,device:kind,user_agent:ua.slice(0,400)};}
function embeddedBrowser(){var ua=navigator.userAgent||'';if(/FBAN|FBAV|FB_IAB|FBIOS|Instagram/i.test(ua))return{name:'Instagram / Facebook',hard:true};if(/TikTok|musical_ly|BytedanceWebview|Bytedance/i.test(ua))return{name:'TikTok',hard:true};if(/Snapchat/i.test(ua))return{name:'Snapchat',hard:true};if(/Line\//i.test(ua))return{name:'LINE',hard:true};if(/WhatsApp/i.test(ua))return{name:'WhatsApp',hard:true};if(/Pinterest/i.test(ua))return{name:'Pinterest',hard:true};if(/\bGSA\//i.test(ua))return{name:'the Google app',hard:false};if(/DuckDuckGo/i.test(ua))return{name:'DuckDuckGo',hard:false};return null;}
function api(path,body,opts){opts=opts||{};return fetch(FN+path,{method:'POST',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON},body:JSON.stringify(body||{}),keepalive:!!opts.keepalive}).then(function(r){return r.json().then(function(j){return{ok:r.ok,status:r.status,data:j};});});}
function fail(title,msg){if($('gateTitle'))$('gateTitle').textContent=title;if($('gateMsg'))$('gateMsg').textContent=msg;show('gateStage');}
function selectEnvironment(env){if(env!=='home'&&env!=='gym')return;S.environment=env;['home','gym'].forEach(function(x){var b=$(x==='home'?'modeHome':'modeGym');var on=x===env;b.classList.toggle('selected',on);b.setAttribute('aria-checked',on?'true':'false');});$('prepBox').classList.add('on');if(env==='home'){$('prepTitle').textContent='Set up at home';$('prepText').textContent='Prop your phone securely, clear enough space to move, and keep your whole body visible.';$('startBtn').textContent='Start Home task';}else{$('prepTitle').textContent='Set up safely at the gym';$('prepText').textContent='Prop your phone where it cannot be hit. Keep yourself and the required equipment visible. Use a controlled demonstration weight.';$('startBtn').textContent='Start Gym task';}$('startBtn').disabled=false;}
function stopStream(){try{if(S.stream)S.stream.getTracks().forEach(function(t){t.stop();});}catch(e){}S.stream=null;}
function camConstraints(facing){var res=IS_MOBILE?{width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:30}}:{width:{ideal:960},height:{ideal:720}};res.facingMode=facing;return{video:res,audio:false};}
function ensureCamera(facing){if(S.stream&&facing===S.facing)return Promise.resolve(S.stream);return navigator.mediaDevices.getUserMedia(camConstraints(facing)).then(function(stream){var track=stream.getVideoTracks()[0];if(!track||track.readyState!=='live'){stream.getTracks().forEach(function(t){t.stop();});throw new Error('camera_not_live');}if(S.stream)stopStream();S.stream=stream;S.facing=facing;var vid=$('cam');vid.srcObject=stream;vid.classList.toggle('mirror',facing==='user');var st=track.getSettings?track.getSettings():{};S.camQuality={width:st.width||0,height:st.height||0,orientation:innerHeight>innerWidth?'portrait':'landscape'};return vid.play().then(function(){startCamFps(vid);return stream;});});}
function startCamFps(vid){stopCamFps();S.camFrames=0;S.camLast=performance.now();if(typeof vid.requestVideoFrameCallback==='function'){var cb=function(now){S.camFrames++;var dt=now-S.camLast;if(dt>=1000){S.camFps=S.camFps?S.camFps*.6+(S.camFrames*1000/dt)*.4:S.camFrames*1000/dt;S.camFrames=0;S.camLast=now;}if(S.stream)S.rvfc=vid.requestVideoFrameCallback(cb);};S.rvfc=vid.requestVideoFrameCallback(cb);}else if(typeof vid.getVideoPlaybackQuality==='function'){var prev=vid.getVideoPlaybackQuality().totalVideoFrames,pt=performance.now();S.camTimer=setInterval(function(){try{var q=vid.getVideoPlaybackQuality(),now=performance.now(),f=q.totalVideoFrames-prev,dt=now-pt;if(dt>0)S.camFps=f*1000/dt;prev=q.totalVideoFrames;pt=now;}catch(e){}},1000);}}
function stopCamFps(){if(S.camTimer)clearInterval(S.camTimer);S.camTimer=null;S.rvfc=null;}
function redeem(){return api('beta-live-start',{invite_token:S.invite,environment:S.environment,previous_exercise:S.previousExercise,device:Object.assign(device(),{camera_quality:S.camQuality})}).then(function(res){if(!res.ok||!res.data||!res.data.session_id)throw new Error(res.data&&res.data.error||'start_failed');S.sessionId=res.data.session_id;S.token=res.data.session_token;S.seq=0;S.task=res.data;S.previousExercise=res.data.exercise;return res.data;});}
var RING_C=2*Math.PI*78;
function ringLoop(){S.ringCurrent+=(S.ringTarget-S.ringCurrent)*.18;var bar=$('ringBar');if(bar){bar.style.strokeDasharray=RING_C;bar.style.strokeDashoffset=RING_C*(1-Math.max(0,Math.min(1,S.ringCurrent)));}S.raf=requestAnimationFrame(ringLoop);}
function startRing(){if(!S.raf)S.raf=requestAnimationFrame(ringLoop);}function stopRing(){if(S.raf)cancelAnimationFrame(S.raf);S.raf=null;}
function setCue(text){var el=$('cueTxt');if(!el||el.textContent===text)return;el.classList.add('swap');setTimeout(function(){el.textContent=text||'';el.classList.remove('swap');},160);}
var VIS_HELP={no_person:'Step into frame — I cannot see you yet',out_of_frame:'Center yourself in the frame',too_far:'Come closer — you are too far away',too_close:'Step back so your whole body fits',partial_person:'Step back so I can see the required body parts',poor_lighting:'Find brighter, even lighting',ready:''};
function framingHelp(state){var vs=state.visibilityState;if(vs&&VIS_HELP[vs]!=null&&vs!=='ready'){var v3=state.v3;if(vs==='partial_person'&&v3&&v3.checklist&&v3.checklist.length){var miss=v3.checklist.filter(function(i){return!i.ok;}).map(function(i){return i.label;});if(miss.length)return'Get your '+miss.slice(0,2).join(' and ')+' in frame';}return VIS_HELP[vs];}return state.visibilityCue||VIS_HELP[vs]||'';}
function progress(state){if(state.holdTargetMs)return{frac:(state.holdMs||0)/state.holdTargetMs,big:Math.round((state.holdMs||0)/1000),small:'of '+Math.round(state.holdTargetMs/1000)+'s hold'};if(state.durationTargetMs)return{frac:(state.clientClaimedDurationMs||0)/state.durationTargetMs,big:Math.round((state.clientClaimedDurationMs||0)/1000),small:'of '+Math.round(state.durationTargetMs/1000)+'s'};if(state.targetReps)return{frac:(state.reps||0)/state.targetReps,big:state.reps||0,small:'of '+state.targetReps+' reps'};return{frac:0,big:state.reps||0,small:'reps'};}
function liveConfidence(state){var v3=state.v3&&state.v3.result;var vis=v3&&v3.requiredLandmarksVisible!=null?v3.requiredLandmarksVisible:(state.trackingConfidence||0);return Math.max(0,Math.min(1,.5*(state.trackingConfidence||0)+.5*vis));}
function onUpdate(state){S.lastState=state;var now=performance.now();if(S.lastInfAt){var dt=now-S.lastInfAt;if(dt>0)S.infFps=S.infFps?S.infFps*.85+(1000/dt)*.15:1000/dt;}S.lastInfAt=now;if(state.poseMs!=null){S.latency.push(state.poseMs);if(S.latency.length>240)S.latency.shift();}if(S.lastTracking===true&&!state.poseTracking)S.trackingLoss++;var changed=S.lastTracking!==null&&!!state.poseTracking!==S.lastTracking;S.lastTracking=!!state.poseTracking;var ready=!!state.poseTracking||state.visibilityState==='ready';if(ready){S.everReady=true;S.lastReadyAt=now;}var p=progress(state);if(p.frac>S.lastProgress+.0001){S.lastProgress=p.frac;S.lastProgressAt=now;}if(state.visibilityState)S.domVis[state.visibilityState]=(S.domVis[state.visibilityState]||0)+1;var pill=$('statusPill'),txt=$('statusTxt');if(state.poseTracking){pill.className='pill good';txt.textContent='Locked on';}else if(state.visibilityState&&state.visibilityState!=='ready'){pill.className='pill adjust';txt.textContent=String(state.visibilityState).replace(/_/g,' ');}else{pill.className='pill adjust';txt.textContent=state.engineStatus==='loading'?'Warming up…':'Get in frame…';}S.ringTarget=p.frac;$('ringBig').textContent=p.big;$('ringSmall').textContent=p.small;setCue(state.poseTracking?(state.lastCue||(state.v3&&state.v3.result&&state.v3.result.cue)||'Keep going'):framingHelp(state));$('confFill').style.width=Math.round(liveConfidence(state)*100)+'%';if(changed)sendEvent(state.poseTracking?'tracking_recovered':'tracking_lost',snap(state));if(now-S.lastHeartbeat>1400){S.lastHeartbeat=now;sendEvent('heartbeat',snap(state));}if(!S.finishing&&!S.completed&&state.canFinish===true&&state.evidenceSufficient===true)autoFinish('completed');}
function snap(state){var p=progress(state);return{environment:S.environment,reps:state.reps||0,rejected_reps:state.clientRejectedReps||0,phase:state.phase||null,tracking:!!state.poseTracking,progress:Math.round(p.frac*100),fps:Math.round(S.infFps||0),camera_fps:Math.round(S.camFps||0),confidence:+liveConfidence(state).toFixed(3),visibility:state.visibilityState||null};}
function percentile(a,q){if(!a.length)return null;var b=a.slice().sort(function(x,y){return x-y;});return Math.round(b[Math.min(b.length-1,Math.floor(q*b.length))]);}
function sendEvent(type,payload){if(!S.token)return;api('beta-live-event',{session_token:S.token,seq:++S.seq,t_ms:S.startedAt?performance.now()-S.startedAt:0,type:type,payload:payload||{}}).catch(function(){});}
function dominantVisibility(){var best=null,n=-1;for(var k in S.domVis)if(S.domVis[k]>n){n=S.domVis[k];best=k;}return best;}
function startWatchdog(){stopWatchdog();S.watchdog=setInterval(function(){if(!S.active||S.finishing||S.completed)return;var now=performance.now(),elapsed=now-S.startedAt;if(S.bgSince&&now-S.bgSince>BG_MS)return failWith('failed','backgrounded_during_session');if(!S.everReady&&elapsed>WARMUP_MS)return failWith('failed','no_pose_acquired'+(dominantVisibility()?':'+dominantVisibility():''));if(elapsed>HARD_CAP_MS)return failWith('timed_out','session_time_cap_reached');},1000);}function stopWatchdog(){if(S.watchdog)clearInterval(S.watchdog);S.watchdog=null;}
function countdown(){var cd=$('countdown'),num=$('cdNum'),seq=['3','2','1','GO'],i=0;cd.style.display='flex';return new Promise(function(resolve){(function step(){if(i>=seq.length){cd.style.display='none';resolve();return;}num.textContent=seq[i];num.style.animation='none';void num.offsetWidth;num.style.animation='';i++;setTimeout(step,i===seq.length?500:850);})();});}
function runSession(){S.active=false;S.warming=true;S.completed=false;S.finishing=false;S.infFps=0;S.lastInfAt=0;S.latency=[];S.trackingLoss=0;S.lastTracking=null;S.lastHeartbeat=0;S.everReady=false;S.lastReadyAt=0;S.lastProgress=0;S.lastProgressAt=0;S.bgSince=0;S.domVis={};S.lastState=null;S.ringTarget=0;S.ringCurrent=0;$('ringBig').textContent='0';setCue('Get into the recommended camera position');startRing();var coach=window.VISION&&VISION.liveCoach?VISION.liveCoach.create({video:$('cam'),overlay:null,task:{id:S.sessionId,title:S.task.title},onUpdate:onUpdate}):null;if(!coach)return abort('engine_unavailable','The live engine could not load.');S.coach=coach;return countdown().then(function(){return coach.start();}).then(function(r){if(!r||r.ok===false)return abort(r&&r.error||'verifier_start_failed',r&&r.message||'Vision could not verify this task live.');S.active=true;S.warming=false;S.startedAt=performance.now();S.lastProgressAt=S.startedAt;startWatchdog();sendEvent('session_started',{environment:S.environment,exercise:S.task.exercise,target_kind:S.task.target_kind,target_value:S.task.target_value,equipment_required:!!S.task.equipment_required,mobile:IS_MOBILE});});}
function collectSummary(status,reason){var state=(S.coach&&S.coach.getState?S.coach.getState():null)||S.lastState||{},telemetry={};try{telemetry.diagnostics=S.coach&&S.coach.getV3Diagnostics?S.coach.getV3Diagnostics():null;}catch(e){}try{telemetry.evidence=S.coach&&S.coach.getV3Evidence?S.coach.getV3Evidence():null;}catch(e){}try{telemetry.coach_summary=S.coach&&S.coach.getCoachSummary?S.coach.getCoachSummary():null;}catch(e){}telemetry.dominant_visibility=dominantVisibility();telemetry.visibility_histogram=S.domVis;telemetry.environment=S.environment;var d=device(),conf=status==='completed'?Math.max(0,Math.min(1,.55*(state.trackingConfidence||0)+.3+.15*(1-(state.clientRejectedReps||0)/((state.reps||0)+(state.clientRejectedReps||0)+1)))):liveConfidence(state);return{completion_status:status,detected_reps:state.reps||0,rejected_reps:state.clientRejectedReps||0,hold_ms:Math.round(state.holdMs||0),valid_duration_ms:Math.round(state.clientClaimedDurationMs||0),confidence:+conf.toFixed(3),camera_quality:Object.assign({},S.camQuality,{camera_fps:S.camFps?+S.camFps.toFixed(1):null,inference_fps:S.infFps?+S.infFps.toFixed(1):null,latency_p50_ms:percentile(S.latency,.5),latency_p95_ms:percentile(S.latency,.95),embedded_browser:(embeddedBrowser()||{}).name||null}),tracking_loss:S.trackingLoss,fps:S.infFps?+S.infFps.toFixed(1):null,latency_ms:percentile(S.latency,.5),browser:d.browser,os:d.os,device:d.device,verifier_engine:'live-proof-v3',verifier_id:S.task&&S.task.verifier_id,verifier_version:S.task&&S.task.verifier_version,failure_reason:reason||null,telemetry:telemetry};}
function autoFinish(status,reason){if(S.finishing)return;S.finishing=true;S.active=false;S.warming=false;stopWatchdog();var summary=collectSummary(status,reason);try{if(S.coach&&S.coach.stop)S.coach.stop();}catch(e){}api('beta-live-finish',{session_token:S.token,summary:summary}).catch(function(){}).then(function(){S.completed=status==='completed';renderDone(status,summary,reason);});}
function failWith(status,reason){autoFinish(status,reason);}function abort(reason,message){autoFinish('failed',reason);if($('doneBanner')){$('doneBanner').style.display='block';$('doneBanner').textContent=message||'Vision could not verify this session.';}}
var REASON_TEXT={no_pose_acquired:'Vision never got a clear view. Reposition your phone and retry.',backgrounded_during_session:'The session was interrupted when the app went into the background.',session_time_cap_reached:'The task was not completed before the session limit.',live_verification_unavailable:'This exercise cannot be verified live yet.',equipment_verification_unavailable:'The required equipment could not be verified.',v3_modules_unavailable:'The vision engine failed to load.'};
function renderDone(status,summary,reason){stopRing();if(status==='completed'){$('doneTitle').textContent='Verified';$('doneSub').textContent='Vision tracked your '+S.environment+' task.';$('doneBanner').style.display='none';$('nextBtn').textContent='Next '+(S.environment==='gym'?'Gym':'Home')+' task';}else{$('doneTitle').textContent=status==='timed_out'?'Timed out':status==='cancelled'?'Cancelled':'Not verified';$('doneSub').textContent='Nothing was accepted.';$('doneBanner').style.display='block';var key=String(reason||'').split(':')[0];$('doneBanner').textContent=REASON_TEXT[key]||(reason?'Reason: '+String(reason).replace(/_/g,' '):'The task was not completed.');$('nextBtn').textContent='Try another '+(S.environment==='gym'?'Gym':'Home')+' task';}var mode=S.task&&S.task.mode;if(mode==='hold'){$('sReps').textContent=Math.round((summary.hold_ms||0)/1000)+'s';$('sRepsK').textContent='held';}else if(mode==='duration'){$('sReps').textContent=Math.round((summary.valid_duration_ms||0)/1000)+'s';$('sRepsK').textContent='moved';}else{$('sReps').textContent=summary.detected_reps||0;$('sRepsK').textContent='reps';}$('sConf').textContent=Math.round((summary.confidence||0)*100)+'%';$('sTime').textContent=Math.round((performance.now()-(S.startedAt||performance.now()))/1000)+'s';$('sFps').textContent=summary.fps?Math.round(summary.fps):'—';show('doneStage');}
function renderTask(task){$('revealEnv').textContent=task.environment==='gym'?'Gym':'Home';$('revealEx').textContent=task.exercise.replace(/_/g,' ');$('revealGoal').textContent=task.title;var cp=task.camera_profile||{};$('revealSetup').textContent=cp.setup||'Position your phone so the full movement stays visible.';$('revealEquipment').textContent=task.equipment_required?'Required equipment: '+(task.equipment_type||'gym equipment'):'No equipment required';$('revealHint').textContent='Warming up the vision engine…';}
function beginFlow(hint){if(!S.environment)return Promise.reject(new Error('invalid_environment'));show('revealStage');$('revealSpin').style.display='';$('revealHint').textContent=hint||'Assigning a supported task…';return ensureCamera(S.facing).then(redeem).then(function(task){renderTask(task);try{if(VISION.liveCoach.preload)VISION.liveCoach.preload();}catch(e){}return new Promise(function(res){setTimeout(res,IS_MOBILE?1700:1900);});}).then(function(){show('camStage');return runSession();});}
function handleStartError(e){$('startBtn').disabled=false;var msg=String(e&&e.message||e);if(/no_environment_exercise_available/.test(msg)){stopStream();show('introStage');if(S.environment==='gym'){$('prepTitle').textContent='Gym verification is still qualifying';$('prepText').textContent='No equipment exercise has passed the public real-camera release gate yet. Gym stays locked rather than pretending. Choose Home for a verified task.';$('startBtn').textContent='Choose Home';$('startBtn').disabled=true;}return;}if(/Permission|NotAllowed|denied/i.test(msg))return fail('Camera needed','Enable camera access, then reopen the link.');if(/NotFound|no camera|Overconstrained/i.test(msg))return fail('No camera found','This device has no usable camera.');if(/invalid_invite/.test(msg))return fail('Invite not valid','Ask for a fresh testing link.');if(/invite_unavailable/.test(msg))return fail('Invite used up','This invite has expired or reached its limit.');fail('Could not start','Please retry. ('+msg.slice(0,70)+')');}
function begin(){$('startBtn').disabled=true;beginFlow('Assigning a supported '+S.environment+' task…').catch(handleStartError);}function nextTask(){$('nextBtn').disabled=true;beginFlow('Assigning your next '+S.environment+' task…').then(function(){$('nextBtn').disabled=false;}).catch(function(e){$('nextBtn').disabled=false;handleStartError(e);});}
function cancelSession(){if(S.active&&!S.completed&&!S.finishing)failWith('cancelled','cancelled_by_tester');else{teardown();show('doneStage');}}function teardown(){stopWatchdog();stopRing();stopCamFps();try{if(S.coach&&S.coach.stop)S.coach.stop();}catch(e){}stopStream();}
function changeMode(){teardown();S.environment=null;S.task=null;S.token=null;S.sessionId=null;['modeHome','modeGym'].forEach(function(id){$(id).classList.remove('selected');$(id).setAttribute('aria-checked','false');});$('prepBox').classList.remove('on');$('startBtn').disabled=true;$('startBtn').textContent='Choose Home or Gym';show('introStage');}
function showBrowserGate(info){show('browserStage');var link=location.href;$('bgName').textContent=info.name;$('bgLink').textContent=link;$('bgCopy').onclick=function(){navigator.clipboard&&navigator.clipboard.writeText(link).then(function(){$('bgCopy').textContent='Copied ✓';}).catch(function(){});};if(info.hard)$('bgContinue').style.display='none';else{$('bgContinue').style.display='';$('bgContinue').onclick=function(){show('introStage');};}}
function init(){if(!CFG.url||!ANON){fail('Unavailable','The beta backend is not configured for this host.');return;}var params=new URLSearchParams(location.search);S.invite=params.get('invite')||params.get('i');if(!S.invite||S.invite.length<16){show('gateStage');return;}$('modeHome').addEventListener('click',function(){selectEnvironment('home');});$('modeGym').addEventListener('click',function(){selectEnvironment('gym');});$('startBtn').addEventListener('click',begin);$('nextBtn').addEventListener('click',nextTask);$('changeModeBtn').addEventListener('click',changeMode);$('finishBtn').addEventListener('click',function(){teardown();fail('Thanks for testing','Your sessions were uploaded. You can close this tab.');});$('closeBtn').addEventListener('click',cancelSession);$('flipBtn').addEventListener('click',function(){ensureCamera(S.facing==='user'?'environment':'user').catch(function(){});});window.addEventListener('pagehide',function(){if((S.active||S.warming)&&!S.completed&&!S.finishing&&S.token)api('beta-live-finish',{session_token:S.token,summary:collectSummary('abandoned','page_hidden')},{keepalive:true}).catch(function(){});});document.addEventListener('visibilitychange',function(){if(document.hidden){if(S.active){S.bgSince=performance.now();sendEvent('backgrounded',{});}}else S.bgSince=0;});var emb=embeddedBrowser();if(emb){showBrowserGate(emb);return;}show('introStage');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
