import { defineDomainPack } from './contract.js';

export const athleteDomainPack = defineDomainPack({
  domainId: 'athlete',
  version: '1.0.0',
  supportedGoalCategories: [
    'sport_performance',
    'position_or_event_performance',
    'technical_skill',
    'tactical_skill',
    'strength_and_conditioning',
    'recovery',
    'training_phase',
    'competition_readiness',
  ],
  milestoneCategories: [
    'technical_benchmark',
    'tactical_competency',
    'physical_performance',
    'training_phase_completion',
    'selection_or_competition',
    'competition_readiness',
  ],
  proofCompatibleEvidenceTypes: [
    {
      id: 'athlete_live_drill',
      proofMode: 'live',
      description: 'Server-reviewed movement or active-duration evidence for a supported drill without claiming unverified sport outcomes.',
      supportedClaimCategoryIds: ['athlete_technical_execution_standard_met', 'athlete_prescribed_session_completed'],
      capturedOutputCategoryIds: ['athlete_performance_series_recorded', 'athlete_conditioning_session_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'athlete_session_photo',
      proofMode: 'photo',
      description: 'A training-plan, session-log, technical frame, result, or coach-defined output image.',
      supportedClaimCategoryIds: ['athlete_technical_execution_standard_met', 'athlete_tactical_decision_demonstrated', 'athlete_prescribed_session_completed', 'athlete_performance_bottleneck_decision_recorded', 'athlete_recovery_readiness_signals_recorded', 'athlete_competition_readiness_verified'],
      capturedOutputCategoryIds: ['athlete_performance_series_recorded', 'athlete_tactical_session_record', 'athlete_conditioning_session_record', 'athlete_performance_review_record', 'athlete_recovery_readiness_record', 'athlete_phase_session_record', 'athlete_competition_preparation_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'athlete_review_voice',
      proofMode: 'voice',
      description: 'A structured technical, tactical, recovery, or competition-readiness review.',
      supportedClaimCategoryIds: ['athlete_tactical_decision_demonstrated', 'athlete_performance_bottleneck_decision_recorded', 'athlete_recovery_readiness_signals_recorded', 'athlete_competition_readiness_verified'],
      capturedOutputCategoryIds: ['athlete_tactical_session_record', 'athlete_performance_review_record', 'athlete_recovery_readiness_record', 'athlete_competition_preparation_record'],
      requiredCaptureCapabilityIds: ['microphone'],
    },
    {
      id: 'athlete_hybrid_performance',
      proofMode: 'hybrid',
      description: 'Movement evidence paired with result, equipment, tactical, or coach-plan evidence.',
      supportedClaimCategoryIds: ['athlete_technical_execution_standard_met', 'athlete_tactical_decision_demonstrated', 'athlete_prescribed_session_completed', 'athlete_competition_readiness_verified'],
      capturedOutputCategoryIds: ['athlete_performance_series_recorded', 'athlete_tactical_session_record', 'athlete_conditioning_session_record', 'athlete_phase_session_record', 'athlete_competition_preparation_record'],
      requiredCaptureCapabilityIds: ['artifact_capture'],
    },
  ],
  professionalWorkUnitTypes: [
    { id: 'athlete_technical_session', description: 'Complete a sport- and position-specific technical practice block against a named execution standard.', compatibleEvidenceTypeIds: ['athlete_live_drill', 'athlete_session_photo', 'athlete_hybrid_performance'], allowedClaimCategoryIds: ['athlete_technical_execution_standard_met'], producedOutputCategoryIds: ['athlete_performance_series_recorded'] },
    { id: 'athlete_tactical_session', description: 'Complete a tactical analysis or representative decision-practice block tied to the athlete role and game model.', compatibleEvidenceTypeIds: ['athlete_session_photo', 'athlete_review_voice', 'athlete_hybrid_performance'], allowedClaimCategoryIds: ['athlete_tactical_decision_demonstrated'], producedOutputCategoryIds: ['athlete_tactical_session_record'] },
    { id: 'athlete_strength_conditioning_session', description: 'Complete the programme-prescribed physical preparation session for the current phase and sport demand.', compatibleEvidenceTypeIds: ['athlete_live_drill', 'athlete_session_photo', 'athlete_hybrid_performance'], allowedClaimCategoryIds: ['athlete_prescribed_session_completed'], producedOutputCategoryIds: ['athlete_conditioning_session_record'] },
    { id: 'athlete_performance_review', description: 'Review competition or training evidence, identify the principal performance bottleneck, and decide the next intervention.', compatibleEvidenceTypeIds: ['athlete_session_photo', 'athlete_review_voice'], allowedClaimCategoryIds: ['athlete_performance_bottleneck_decision_recorded'], producedOutputCategoryIds: ['athlete_performance_review_record'] },
    { id: 'athlete_recovery_protocol', description: 'Complete the assigned recovery or return-to-training protocol and record readiness signals.', compatibleEvidenceTypeIds: ['athlete_session_photo', 'athlete_review_voice'], allowedClaimCategoryIds: ['athlete_recovery_readiness_signals_recorded'], producedOutputCategoryIds: ['athlete_recovery_readiness_record'] },
    { id: 'athlete_phase_session', description: 'Execute the coach or programme session appropriate to base, build, peak, taper, competition, or transition phase.', compatibleEvidenceTypeIds: ['athlete_session_photo', 'athlete_hybrid_performance'], allowedClaimCategoryIds: ['athlete_prescribed_session_completed'], producedOutputCategoryIds: ['athlete_phase_session_record'] },
    { id: 'athlete_competition_preparation', description: 'Complete a competition-readiness unit covering the relevant technical, tactical, equipment, recovery, and schedule requirements.', compatibleEvidenceTypeIds: ['athlete_session_photo', 'athlete_review_voice', 'athlete_hybrid_performance'], allowedClaimCategoryIds: ['athlete_competition_readiness_verified'], producedOutputCategoryIds: ['athlete_competition_preparation_record'] },
  ],
  prerequisiteCategories: [
    'sport_position_or_event_defined',
    'current_training_phase',
    'technical_foundation',
    'coach_or_programme_context',
    'equipment_and_venue_access',
    'medical_clearance_when_indicated',
  ],
  bottleneckCategories: [
    'technical_execution_gap',
    'tactical_decision_gap',
    'sport_specific_physical_gap',
    'recovery_or_load_issue',
    'programme_adherence',
    'competition_preparation_gap',
  ],
  progressSignals: [
    'sport_specific_benchmark_change',
    'technical_success_rate',
    'tactical_decision_quality',
    'programme_session_completion',
    'competition_result_or_selection_evidence',
    'readiness_trend',
  ],
  capabilitySignals: [
    'repeatable_technical_execution',
    'representative_tactical_decisions',
    'sport_specific_speed_power_or_endurance',
    'training_load_tolerance',
    'competition_execution_quality',
  ],
  constraintSignals: [
    'coach_programme_requirement',
    'training_phase_load',
    'competition_calendar',
    'venue_team_or_partner_access',
    'injury_or_return_to_play_limit',
    'equipment_requirement',
  ],
  recoveryReadinessSignals: [
    'sleep_quality',
    'soreness_and_pain',
    'energy_and_motivation',
    'training_load_response',
    'competition_readiness',
  ],
  hardScalingRules: [
    { id: 'athlete_hard_sport_edge', description: 'Target the highest-impact edge of proven sport-, position-, event-, and phase-specific capability.' },
    { id: 'athlete_hard_representative_demand', description: 'Increase representative technical, tactical, physical, or competition demand only as the programme and evidence support.' },
    { id: 'athlete_hard_phase_integrity', description: 'Preserve coach-plan sequencing, training-phase intent, recovery limits, and technical quality.' },
  ],
  mediumScalingRules: [
    { id: 'athlete_medium_same_sport_outcome', description: 'Keep the same sport skill, tactical purpose, physical quality, phase, and active milestone as Hard.' },
    { id: 'athlete_medium_reduce_dose', description: 'Reduce repetitions, duration, opponent complexity, drill constraints, or nonessential conditioning volume.' },
    { id: 'athlete_medium_preserve_specificity', description: 'Do not substitute generic conditioning for the specific technical, tactical, or programme outcome.' },
  ],
  fixedMissionConditions: [
    { id: 'athlete_fixed_coach_session', description: 'A coach, team, governing body, selection process, or competition requires an exact session or event.' },
    { id: 'athlete_fixed_competition', description: 'A scheduled match, race, meet, trial, weigh-in, or competition protocol cannot be rescaled.' },
  ],
  clarificationTriggers: [
    { id: 'athlete_clarify_sport_role', description: 'The sport, position, discipline, event, or competitive level is unknown.' },
    { id: 'athlete_clarify_phase', description: 'The training phase, competition schedule, current programme, or coach requirement is missing.' },
    { id: 'athlete_clarify_bottleneck', description: 'No technical, tactical, physical, recovery, or readiness evidence identifies the current bottleneck.' },
    { id: 'athlete_clarify_safety', description: 'Pain, injury, return-to-play status, load tolerance, or medical guidance could change the mission.' },
  ],
  safetyIntegrityGates: [
    { id: 'athlete_gate_programme_connection', description: 'Require a direct connection to the sport, role or event, programme, training phase, and evidenced bottleneck.' },
    { id: 'athlete_gate_no_reckless_load', description: 'Reject reckless overload, overtraining, unsafe weight cutting, punishment conditioning, or return through concerning pain.' },
    { id: 'athlete_gate_result_honesty', description: 'Do not claim technical success, score, distance, speed, load, or competition readiness beyond what evidence can prove.' },
    { id: 'athlete_gate_coach_and_medical_boundary', description: 'Preserve valid coach plans and qualified return-to-play or medical requirements; do not fabricate them.' },
  ],
  externalPlanRules: [
    { id: 'athlete_external_preserve_programme', description: 'Preserve valid coach, team, clinician, governing-body, and competition plans, sequencing, deadlines, and versions.' },
    { id: 'athlete_external_label_additions', description: 'Label VISION-added guidance separately and obtain approval before changing active coach or professional mission state.' },
  ],
  forbiddenGenericMissionPatterns: [
    { id: 'athlete_forbid_generic_conditioning', description: 'Generic conditioning unrelated to the sport, position or event, training phase, programme, or performance bottleneck.' },
    { id: 'athlete_forbid_relabelled_fitness', description: 'A general fitness workout relabelled with the sport name but lacking sport-specific technical, tactical, or programme relevance.' },
    { id: 'athlete_forbid_phase_conflict', description: 'A high-load or high-fatigue task that conflicts with taper, competition, recovery, or return-to-play requirements.' },
  ],
  evaluationRuleIds: [
    'athlete_sport_position_event_specificity',
    'athlete_training_phase_correctness',
    'athlete_performance_bottleneck_leverage',
    'athlete_coach_programme_alignment',
    'athlete_recovery_and_safety_fit',
  ],
});
