import { defineDomainPack } from './contract.js';

export const creatorDomainPack = defineDomainPack({
  domainId: 'creator',
  version: '1.0.0',
  supportedGoalCategories: [
    'ideation',
    'production',
    'editing',
    'publishing',
    'distribution',
    'audience_learning',
    'consistency_systems',
    'monetisation',
  ],
  milestoneCategories: [
    'validated_content_direction',
    'production_completion',
    'publication_cadence',
    'distribution_result',
    'audience_learning',
    'monetisation_outcome',
  ],
  proofCompatibleEvidenceTypes: [
    {
      id: 'creator_artifact_photo',
      proofMode: 'photo',
      description: 'A privacy-safe image of a script, edit, published asset, distribution output, or audience analysis.',
      supportedClaimCategoryIds: ['creator_content_brief_finalized', 'creator_production_asset_completed', 'creator_editing_standard_met', 'creator_rights_cleared_asset_published', 'creator_distribution_outcome_tracked', 'creator_audience_decision_recorded', 'creator_monetisation_outcome_recorded'],
      capturedOutputCategoryIds: ['creator_content_brief_record', 'creator_production_asset_record', 'creator_edited_asset_record', 'creator_publication_record', 'creator_distribution_campaign_record', 'creator_audience_analysis_record', 'creator_monetisation_test_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'creator_review_voice',
      proofMode: 'voice',
      description: 'A structured creative rationale, edit review, audience-learning synthesis, or post-publication analysis.',
      supportedClaimCategoryIds: ['creator_content_brief_finalized', 'creator_editing_standard_met', 'creator_audience_decision_recorded'],
      capturedOutputCategoryIds: ['creator_content_brief_record', 'creator_edited_asset_record', 'creator_audience_analysis_record'],
      requiredCaptureCapabilityIds: ['microphone'],
    },
    {
      id: 'creator_hybrid_release',
      proofMode: 'hybrid',
      description: 'Creative artefact evidence paired with distribution, publishing, or strategic explanation.',
      supportedClaimCategoryIds: ['creator_production_asset_completed', 'creator_rights_cleared_asset_published', 'creator_distribution_outcome_tracked', 'creator_monetisation_outcome_recorded'],
      capturedOutputCategoryIds: ['creator_production_asset_record', 'creator_publication_record', 'creator_distribution_campaign_record', 'creator_monetisation_test_record'],
      requiredCaptureCapabilityIds: ['artifact_capture'],
    },
  ],
  professionalWorkUnitTypes: [
    { id: 'creator_content_brief', description: 'Produce a decision-ready brief for a named medium, platform, audience, promise, format, and success signal.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_review_voice'], allowedClaimCategoryIds: ['creator_content_brief_finalized'], producedOutputCategoryIds: ['creator_content_brief_record'] },
    { id: 'creator_production_block', description: 'Complete a coherent production unit such as a script, shoot, recording, illustration, article, or asset set.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_hybrid_release'], allowedClaimCategoryIds: ['creator_production_asset_completed'], producedOutputCategoryIds: ['creator_production_asset_record'] },
    { id: 'creator_editing_pass', description: 'Complete a bounded structural, narrative, visual, audio, or copy edit against the format standard.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_review_voice'], allowedClaimCategoryIds: ['creator_editing_standard_met'], producedOutputCategoryIds: ['creator_edited_asset_record'] },
    { id: 'creator_publication_release', description: 'Publish a finished work to the intended platform with required packaging and quality checks.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_hybrid_release'], allowedClaimCategoryIds: ['creator_rights_cleared_asset_published'], producedOutputCategoryIds: ['creator_publication_record'] },
    { id: 'creator_distribution_campaign', description: 'Execute a platform-appropriate distribution block with a defined audience, channel, message, and tracked outcome.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_hybrid_release'], allowedClaimCategoryIds: ['creator_distribution_outcome_tracked'], producedOutputCategoryIds: ['creator_distribution_campaign_record'] },
    { id: 'creator_audience_analysis', description: 'Analyse specific audience behaviour or feedback and turn it into one evidence-supported creative decision.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_review_voice'], allowedClaimCategoryIds: ['creator_audience_decision_recorded'], producedOutputCategoryIds: ['creator_audience_analysis_record'] },
    { id: 'creator_monetisation_test', description: 'Run a bounded offer, sponsorship, product, membership, or conversion test connected to the actual audience and medium.', compatibleEvidenceTypeIds: ['creator_artifact_photo', 'creator_hybrid_release'], allowedClaimCategoryIds: ['creator_monetisation_outcome_recorded'], producedOutputCategoryIds: ['creator_monetisation_test_record'] },
  ],
  prerequisiteCategories: [
    'defined_medium_and_platform',
    'defined_audience',
    'current_project_state',
    'production_tool_access',
    'rights_and_permissions',
  ],
  bottleneckCategories: [
    'weak_idea_selection',
    'production_throughput',
    'editing_quality',
    'publishing_friction',
    'distribution_reach',
    'audience_mismatch',
    'monetisation_conversion',
  ],
  progressSignals: [
    'finished_assets',
    'published_outputs',
    'qualified_reach_or_engagement',
    'audience_learning_decisions',
    'conversion_or_revenue_outcome',
    'cadence_reliability',
  ],
  capabilitySignals: [
    'medium_specific_craft',
    'production_completion_quality',
    'editing_judgement',
    'platform_packaging_skill',
    'audience_interpretation',
  ],
  constraintSignals: [
    'available_production_time',
    'tool_and_location_access',
    'collaborator_dependency',
    'platform_requirement',
    'rights_or_sponsorship_obligation',
  ],
  recoveryReadinessSignals: [
    'creative_fatigue',
    'production_load_sustainability',
    'performance_or_voice_readiness',
  ],
  hardScalingRules: [
    { id: 'creator_hard_current_bottleneck', description: 'Increase the consequence or completeness of the work unit that addresses the current project or audience bottleneck.' },
    { id: 'creator_hard_platform_specificity', description: 'Require medium-, platform-, audience-, and stage-specific execution rather than generic creator activity.' },
    { id: 'creator_hard_finished_output', description: 'Prefer a finished creative, publication, distribution, learning, or monetisation output over open-ended effort.' },
  ],
  mediumScalingRules: [
    { id: 'creator_medium_same_project', description: 'Keep the same project, medium, platform, audience, creative principle, and intended outcome as Hard.' },
    { id: 'creator_medium_reduce_nonessential_scope', description: 'Reduce length, number of assets, edit layers, distribution channels, or test size without changing the core output.' },
    { id: 'creator_medium_preserve_publishable_value', description: 'Retain a coherent, usable result rather than replacing production or publishing with generic ideation.' },
  ],
  fixedMissionConditions: [
    { id: 'creator_fixed_release_commitment', description: 'A client, sponsor, collaborator, live event, platform booking, or contracted publication fixes the deliverable.' },
    { id: 'creator_fixed_format_requirement', description: 'A commissioned brief or platform submission requires an exact format, length, or release time.' },
  ],
  clarificationTriggers: [
    { id: 'creator_clarify_medium', description: 'The medium, platform, format, or production workflow is unknown.' },
    { id: 'creator_clarify_audience', description: 'The intended audience and value promise are not defined.' },
    { id: 'creator_clarify_project_stage', description: 'The current project, stage, completed work, or next blocked output is unclear.' },
    { id: 'creator_clarify_rights', description: 'Rights, permissions, sponsorship, or client requirements could constrain the work.' },
  ],
  safetyIntegrityGates: [
    { id: 'creator_gate_rights_and_attribution', description: 'Reject plagiarism, rights violations, deceptive attribution, undisclosed impersonation, or fabricated audience evidence.' },
    { id: 'creator_gate_project_connection', description: 'Require a direct connection to the named medium, platform, audience, current project, and bottleneck.' },
    { id: 'creator_gate_no_harmful_distribution', description: 'Block illegal, abusive, privacy-invasive, or dangerously deceptive content and distribution tactics.' },
    { id: 'creator_gate_honest_metrics', description: 'Do not fabricate reach, engagement, conversion, sponsorship, or revenue outcomes.' },
  ],
  externalPlanRules: [
    { id: 'creator_external_preserve_brief', description: 'Preserve valid client, editor, sponsor, collaborator, or platform brief requirements, deadlines, outcomes, and versions.' },
    { id: 'creator_external_label_additions', description: 'Label VISION-added creative guidance separately and require approval before changing an active professional brief.' },
  ],
  forbiddenGenericMissionPatterns: [
    { id: 'creator_forbid_post_consistently', description: 'Post consistently with no medium, platform, audience, stage, project, bottleneck, or defined output.' },
    { id: 'creator_forbid_idea_list_escape', description: 'Generate more ideas when the evidenced bottleneck is production, editing, publishing, distribution, or monetisation.' },
    { id: 'creator_forbid_platform_agnostic_growth', description: 'Generic grow your audience activity that ignores the platform mechanics, content format, audience evidence, and current project.' },
  ],
  evaluationRuleIds: [
    'creator_medium_platform_audience_match',
    'creator_current_project_bottleneck',
    'creator_complete_creative_output',
    'creator_distribution_or_learning_value',
    'creator_rights_and_metric_integrity',
  ],
});
