import { defineDomainPack } from './contract.js';

export const fitnessDomainPack = defineDomainPack({
  domainId: 'fitness',
  version: '1.0.0',
  supportedGoalCategories: [
    'hypertrophy',
    'strength',
    'fat_loss',
    'conditioning',
    'movement_skill',
    'recovery',
    'programme_adherence',
  ],
  milestoneCategories: [
    'body_composition_outcome',
    'strength_performance',
    'conditioning_benchmark',
    'movement_competency',
    'training_block_completion',
    'recovery_stability',
  ],
  proofCompatibleEvidenceTypes: [
    {
      id: 'fitness_live_session',
      proofMode: 'live',
      description: 'Server-reviewed movement, repetition, hold, or active-duration evidence without claiming unverified load.',
      supportedClaimCategoryIds: ['fitness_prescribed_sets_completed', 'fitness_progressive_load_recorded', 'fitness_conditioning_benchmark_recorded', 'fitness_technical_standard_demonstrated'],
      capturedOutputCategoryIds: ['fitness_hypertrophy_session_record', 'fitness_conditioning_session_record', 'fitness_movement_practice_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'fitness_training_log_photo',
      proofMode: 'photo',
      description: 'A legible programme or training-log output showing prescribed and completed work.',
      supportedClaimCategoryIds: ['fitness_prescribed_sets_completed', 'fitness_progressive_load_recorded', 'fitness_conditioning_benchmark_recorded', 'fitness_progression_decision_recorded', 'fitness_recovery_readiness_signals_recorded'],
      capturedOutputCategoryIds: ['fitness_hypertrophy_session_record', 'fitness_strength_session_record', 'fitness_conditioning_session_record', 'fitness_programme_review_record', 'fitness_recovery_readiness_record', 'fitness_adherence_block_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'fitness_checkin_voice',
      proofMode: 'voice',
      description: 'A structured recovery, pain, exertion, or programme-adherence check-in.',
      supportedClaimCategoryIds: ['fitness_progression_decision_recorded', 'fitness_recovery_readiness_signals_recorded'],
      capturedOutputCategoryIds: ['fitness_programme_review_record', 'fitness_recovery_readiness_record'],
      requiredCaptureCapabilityIds: ['microphone'],
    },
    {
      id: 'fitness_hybrid_session',
      proofMode: 'hybrid',
      description: 'Movement evidence paired with setup, equipment, or training-log evidence when one modality cannot prove the full session.',
      supportedClaimCategoryIds: ['fitness_prescribed_sets_completed', 'fitness_progressive_load_recorded', 'fitness_technical_standard_demonstrated'],
      capturedOutputCategoryIds: ['fitness_hypertrophy_session_record', 'fitness_strength_session_record', 'fitness_movement_practice_record', 'fitness_adherence_block_record'],
      requiredCaptureCapabilityIds: ['artifact_capture'],
    },
  ],
  professionalWorkUnitTypes: [
    { id: 'fitness_hypertrophy_session', description: 'Complete a programme-prescribed hypertrophy session with target muscles, working sets, effort, and progression intent recorded.', compatibleEvidenceTypeIds: ['fitness_live_session', 'fitness_training_log_photo', 'fitness_hybrid_session'], allowedClaimCategoryIds: ['fitness_prescribed_sets_completed', 'fitness_progressive_load_recorded'], producedOutputCategoryIds: ['fitness_hypertrophy_session_record'] },
    { id: 'fitness_strength_session', description: 'Complete a strength session built around the programmed lift, load intent, rest structure, and quality constraints.', compatibleEvidenceTypeIds: ['fitness_training_log_photo', 'fitness_hybrid_session'], allowedClaimCategoryIds: ['fitness_prescribed_sets_completed', 'fitness_progressive_load_recorded'], producedOutputCategoryIds: ['fitness_strength_session_record'] },
    { id: 'fitness_conditioning_session', description: 'Complete a conditioning session tied to the current energy-system or performance benchmark.', compatibleEvidenceTypeIds: ['fitness_live_session', 'fitness_training_log_photo'], allowedClaimCategoryIds: ['fitness_prescribed_sets_completed', 'fitness_conditioning_benchmark_recorded'], producedOutputCategoryIds: ['fitness_conditioning_session_record'] },
    { id: 'fitness_movement_practice', description: 'Perform a bounded movement-skill practice block against a named technical standard.', compatibleEvidenceTypeIds: ['fitness_live_session', 'fitness_hybrid_session'], allowedClaimCategoryIds: ['fitness_technical_standard_demonstrated'], producedOutputCategoryIds: ['fitness_movement_practice_record'] },
    { id: 'fitness_programme_review', description: 'Review logged training against the active programme and make an evidence-supported progression or deload decision.', compatibleEvidenceTypeIds: ['fitness_training_log_photo', 'fitness_checkin_voice'], allowedClaimCategoryIds: ['fitness_progression_decision_recorded'], producedOutputCategoryIds: ['fitness_programme_review_record'] },
    { id: 'fitness_recovery_protocol', description: 'Complete an assigned recovery protocol and record the readiness signals required for the next training decision.', compatibleEvidenceTypeIds: ['fitness_checkin_voice', 'fitness_training_log_photo'], allowedClaimCategoryIds: ['fitness_recovery_readiness_signals_recorded'], producedOutputCategoryIds: ['fitness_recovery_readiness_record'] },
    { id: 'fitness_adherence_block', description: 'Complete the programme-defined session or weekly block without replacing it with unrelated exercise.', compatibleEvidenceTypeIds: ['fitness_training_log_photo', 'fitness_hybrid_session'], allowedClaimCategoryIds: ['fitness_prescribed_sets_completed'], producedOutputCategoryIds: ['fitness_adherence_block_record'] },
  ],
  prerequisiteCategories: [
    'movement_competency',
    'equipment_access',
    'programme_baseline',
    'load_tolerance',
    'medical_clearance_when_indicated',
  ],
  bottleneckCategories: [
    'insufficient_progressive_overload',
    'technical_limit',
    'programme_non_adherence',
    'recovery_deficit',
    'conditioning_specificity_gap',
    'nutrition_or_energy_mismatch',
  ],
  progressSignals: [
    'programme_work_completed',
    'load_or_volume_progression',
    'benchmark_performance_change',
    'body_composition_trend',
    'adherence_rate',
  ],
  capabilitySignals: [
    'repeatable_technique_quality',
    'tolerated_training_volume',
    'verified_strength_or_conditioning_output',
    'movement_range_and_control',
  ],
  constraintSignals: [
    'available_equipment',
    'session_time_window',
    'pain_or_injury_limitation',
    'training_environment',
    'professional_plan_requirement',
  ],
  recoveryReadinessSignals: [
    'sleep_quality',
    'soreness',
    'energy',
    'pain',
    'performance_readiness',
  ],
  hardScalingRules: [
    { id: 'fitness_hard_programme_edge', description: 'Target the highest-impact edge of proven capacity within the active programme, not an invented maximum-effort test.' },
    { id: 'fitness_hard_progressive_dose', description: 'Increase only the programme-relevant load, volume, density, complexity, or pace that the current evidence supports.' },
    { id: 'fitness_hard_quality_preserved', description: 'Preserve movement quality, recovery limits, and the professional principle while increasing challenge.' },
  ],
  mediumScalingRules: [
    { id: 'fitness_medium_same_session', description: 'Keep the same movement pattern, training purpose, muscle group or energy system, and active milestone.' },
    { id: 'fitness_medium_reduce_dose', description: 'Reduce nonessential sets, duration, density, or accessory scope without substituting an unrelated easy exercise.' },
    { id: 'fitness_medium_preserve_stimulus', description: 'Retain a meaningful minimum training stimulus and the same evidence standard.' },
  ],
  fixedMissionConditions: [
    { id: 'fitness_fixed_coach_session', description: 'A coach, clinician, competition, or programme requires an exact session that cannot be safely or legitimately scaled.' },
    { id: 'fitness_fixed_assessment', description: 'A scheduled assessment protocol requires a fixed sequence or dose for comparable results.' },
  ],
  clarificationTriggers: [
    { id: 'fitness_clarify_programme', description: 'The current programme, training phase, or prescribed session is unknown.' },
    { id: 'fitness_clarify_target', description: 'The numeric or qualitative fitness target lacks a timeframe, measurement method, or current baseline.' },
    { id: 'fitness_clarify_safety', description: 'Pain, injury, medical limitation, or recovery status could materially change the safe mission.' },
    { id: 'fitness_clarify_equipment', description: 'The mission depends on equipment or load that has not been confirmed available.' },
  ],
  safetyIntegrityGates: [
    { id: 'fitness_gate_no_extreme_practice', description: 'Reject extreme dieting, punishment workouts, reckless overload, overtraining, or training through concerning pain.' },
    { id: 'fitness_gate_programme_connection', description: 'Require an explicit connection to the actual programme, weakness, recovery need, or active milestone.' },
    { id: 'fitness_gate_honest_load_proof', description: 'Never claim that external load, body composition, or clinical recovery was verified when the evidence cannot prove it.' },
    { id: 'fitness_gate_qualified_care', description: 'Escalate warning signs or medical questions to an appropriate qualified professional.' },
  ],
  externalPlanRules: [
    { id: 'fitness_external_preserve_programme', description: 'Preserve a valid coach or clinician programme sequence, dose, deadlines, outcomes, and version history.' },
    { id: 'fitness_external_label_additions', description: 'Label any VISION-added guidance separately and never invent or silently rewrite the professional strategy.' },
  ],
  forbiddenGenericMissionPatterns: [
    { id: 'fitness_forbid_arbitrary_pushups', description: 'Arbitrary push-ups selected only because the goal is labelled fitness or names an upper-body outcome.' },
    { id: 'fitness_forbid_generic_walking', description: 'Generic walking unrelated to the prescribed programme, conditioning target, recovery assignment, or active bottleneck.' },
    { id: 'fitness_forbid_unrelated_exercise', description: 'Any exercise dose with no plausible connection to the specific weakness, progression state, or milestone.' },
  ],
  evaluationRuleIds: [
    'fitness_goal_category_match',
    'fitness_programme_and_phase_match',
    'fitness_progressive_stimulus_adequacy',
    'fitness_recovery_and_safety_fit',
    'fitness_proof_claim_honesty',
  ],
});
