import { defineDomainPack } from './contract.js';

export const founderDomainPack = defineDomainPack({
  domainId: 'founder',
  version: '1.0.0',
  supportedGoalCategories: [
    'validation',
    'customer_discovery',
    'sales',
    'product_delivery',
    'retention',
    'operations',
    'strategy',
  ],
  milestoneCategories: [
    'validated_problem',
    'qualified_customer_evidence',
    'revenue_outcome',
    'product_release',
    'retention_threshold',
    'operating_system',
  ],
  proofCompatibleEvidenceTypes: [
    {
      id: 'founder_artifact_photo',
      proofMode: 'photo',
      description: 'A privacy-safe image of a shipped product, analysis, sales artefact, or operating output.',
      supportedClaimCategoryIds: ['founder_qualified_customer_contact_completed', 'founder_customer_commitment_obtained', 'founder_usable_product_output_shipped', 'founder_retention_decision_recorded', 'founder_operating_process_implemented', 'founder_strategy_decision_recorded'],
      capturedOutputCategoryIds: ['founder_customer_interview_synthesis_record', 'founder_sales_outcome_log', 'founder_product_delivery_record', 'founder_retention_analysis_record', 'founder_operating_process_record', 'founder_strategy_decision_record', 'founder_offer_test_outcome_log'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'founder_outcome_voice',
      proofMode: 'voice',
      description: 'A structured account of customer evidence, decisions, objections, and next actions.',
      supportedClaimCategoryIds: ['founder_qualified_customer_contact_completed', 'founder_customer_commitment_obtained', 'founder_strategy_decision_recorded'],
      capturedOutputCategoryIds: ['founder_customer_interview_synthesis_record', 'founder_sales_outcome_log', 'founder_strategy_decision_record', 'founder_offer_test_outcome_log'],
      requiredCaptureCapabilityIds: ['microphone'],
    },
    {
      id: 'founder_hybrid_delivery',
      proofMode: 'hybrid',
      description: 'Output evidence paired with a structured explanation when the artefact alone cannot prove strategic quality.',
      supportedClaimCategoryIds: ['founder_qualified_customer_contact_completed', 'founder_usable_product_output_shipped', 'founder_retention_decision_recorded', 'founder_operating_process_implemented', 'founder_strategy_decision_recorded'],
      capturedOutputCategoryIds: ['founder_customer_interview_synthesis_record', 'founder_product_delivery_record', 'founder_retention_analysis_record', 'founder_operating_process_record', 'founder_strategy_decision_record'],
      requiredCaptureCapabilityIds: ['artifact_capture'],
    },
  ],
  professionalWorkUnitTypes: [
    { id: 'founder_customer_interview_set', description: 'Conduct and synthesise a bounded set of customer interviews against one decision-relevant hypothesis.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_outcome_voice', 'founder_hybrid_delivery'], allowedClaimCategoryIds: ['founder_qualified_customer_contact_completed'], producedOutputCategoryIds: ['founder_customer_interview_synthesis_record'] },
    { id: 'founder_sales_outreach_block', description: 'Execute a complete prospecting or follow-up block with a defined segment, offer, ask, and recorded outcomes.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_outcome_voice'], allowedClaimCategoryIds: ['founder_qualified_customer_contact_completed', 'founder_customer_commitment_obtained'], producedOutputCategoryIds: ['founder_sales_outcome_log'] },
    { id: 'founder_product_delivery_slice', description: 'Ship a usable product slice that resolves a named customer problem and can produce feedback.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_hybrid_delivery'], allowedClaimCategoryIds: ['founder_usable_product_output_shipped'], producedOutputCategoryIds: ['founder_product_delivery_record'] },
    { id: 'founder_retention_analysis', description: 'Analyse a defined cohort or customer set, identify the principal retention failure, and decide the next intervention.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_hybrid_delivery'], allowedClaimCategoryIds: ['founder_retention_decision_recorded'], producedOutputCategoryIds: ['founder_retention_analysis_record'] },
    { id: 'founder_operating_process', description: 'Implement or repair an operating process whose absence is blocking reliable delivery, sales, or support.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_hybrid_delivery'], allowedClaimCategoryIds: ['founder_operating_process_implemented'], producedOutputCategoryIds: ['founder_operating_process_record'] },
    { id: 'founder_strategy_decision', description: 'Make a bounded strategic decision from explicit market, customer, financial, and execution evidence.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_outcome_voice', 'founder_hybrid_delivery'], allowedClaimCategoryIds: ['founder_strategy_decision_recorded'], producedOutputCategoryIds: ['founder_strategy_decision_record'] },
    { id: 'founder_offer_test', description: 'Run an end-to-end offer test with a target customer, value proposition, price or commitment ask, and outcome record.', compatibleEvidenceTypeIds: ['founder_artifact_photo', 'founder_outcome_voice'], allowedClaimCategoryIds: ['founder_customer_commitment_obtained'], producedOutputCategoryIds: ['founder_offer_test_outcome_log'] },
  ],
  prerequisiteCategories: [
    'defined_customer_segment',
    'decision_relevant_hypothesis',
    'usable_offer_or_product',
    'outreach_channel_access',
    'delivery_capacity',
  ],
  bottleneckCategories: [
    'insufficient_customer_evidence',
    'weak_demand',
    'sales_conversion',
    'delivery_throughput',
    'retention_failure',
    'operational_constraint',
    'strategic_ambiguity',
  ],
  progressSignals: [
    'qualified_conversations_completed',
    'commitments_or_revenue_won',
    'product_value_shipped',
    'retention_or_repeat_usage_change',
    'cycle_time_reduction',
  ],
  capabilitySignals: [
    'customer_interview_quality',
    'sales_execution_quality',
    'product_delivery_reliability',
    'evidence_based_decision_quality',
    'operating_leverage_created',
  ],
  constraintSignals: [
    'runway_and_budget',
    'team_capacity',
    'customer_access',
    'technical_delivery_limit',
    'legal_or_contractual_requirement',
  ],
  recoveryReadinessSignals: [
    'founder_workload_sustainability',
    'decision_fatigue',
    'team_capacity_recovery',
  ],
  hardScalingRules: [
    { id: 'founder_hard_bottleneck_attack', description: 'Increase the size or consequence of the complete work unit that attacks the evidenced business bottleneck.' },
    { id: 'founder_hard_market_contact', description: 'Prefer stronger contact with market reality, commitment, delivery, or retained usage over more internal speculation.' },
    { id: 'founder_hard_decision_output', description: 'Require a usable business outcome or decision, not additional activity without a decision consequence.' },
  ],
  mediumScalingRules: [
    { id: 'founder_medium_same_hypothesis', description: 'Keep the same customer, hypothesis, offer, product outcome, or operating problem as Hard.' },
    { id: 'founder_medium_reduce_batch', description: 'Reduce the number of interviews, prospects, product scope, or analysis depth while preserving a decision-useful result.' },
    { id: 'founder_medium_preserve_external_signal', description: 'Do not replace customer, sales, delivery, or retention work with internal brainstorming or administration.' },
  ],
  fixedMissionConditions: [
    { id: 'founder_fixed_external_commitment', description: 'A signed customer, investor, regulatory, payroll, tax, or contractual deadline fixes the required deliverable.' },
    { id: 'founder_fixed_live_event', description: 'A scheduled launch, sales call, board meeting, or customer delivery cannot be meaningfully rescaled.' },
  ],
  clarificationTriggers: [
    { id: 'founder_clarify_bottleneck', description: 'The current business bottleneck is not supported by customer, revenue, delivery, retention, or operating evidence.' },
    { id: 'founder_clarify_customer', description: 'The target customer, user, buyer, or decision maker is undefined.' },
    { id: 'founder_clarify_stage', description: 'The business stage and current product or offer state are unknown.' },
    { id: 'founder_clarify_obligation', description: 'An external deadline or professional requirement may make the mission Fixed.' },
  ],
  safetyIntegrityGates: [
    { id: 'founder_gate_no_fabricated_demand', description: 'Reject fabricated customer evidence, deceptive claims, fake testimonials, or misrepresented traction.' },
    { id: 'founder_gate_legal_and_contractual', description: 'Block illegal, suspicious, privacy-invasive, or contract-breaching work.' },
    { id: 'founder_gate_bottleneck_evidence', description: 'Require evidence that the mission attacks the current business bottleneck rather than a comfortable side task.' },
    { id: 'founder_gate_no_professional_fabrication', description: 'Do not invent legal, financial, regulatory, or licensed professional requirements.' },
  ],
  externalPlanRules: [
    { id: 'founder_external_preserve_commitments', description: 'Preserve valid board, investor, adviser, client, or accelerator plan requirements, deadlines, outcomes, and versions.' },
    { id: 'founder_external_label_additions', description: 'Label VISION-added business guidance separately and require approval before changing an active external commitment.' },
  ],
  forbiddenGenericMissionPatterns: [
    { id: 'founder_forbid_brainstorm_escape', description: 'Brainstorming new ideas when validation, sales, delivery, or retention is the evidenced bottleneck.' },
    { id: 'founder_forbid_vanity_admin', description: 'Polishing internal documents, branding, or tooling with no current decision, customer, delivery, or operating consequence.' },
    { id: 'founder_forbid_context_free_outreach', description: 'Generic networking or outreach with no target segment, offer, ask, or tracked outcome.' },
  ],
  evaluationRuleIds: [
    'founder_bottleneck_leverage',
    'founder_market_reality_contact',
    'founder_complete_business_output',
    'founder_stage_and_capacity_fit',
    'founder_integrity_and_legality',
  ],
});
