import { defineDomainPack } from './contract.js';

export const learningDomainPack = defineDomainPack({
  domainId: 'learning',
  version: '1.0.0',
  supportedGoalCategories: [
    'assessment_output',
    'rubric_mastery',
    'knowledge_gap',
    'recall',
    'application',
    'drafting',
    'revision',
    'submission_readiness',
  ],
  milestoneCategories: [
    'diagnostic_baseline',
    'topic_mastery',
    'draft_completion',
    'rubric_threshold',
    'practice_assessment',
    'submission_ready',
  ],
  proofCompatibleEvidenceTypes: [
    {
      id: 'learning_output_photo',
      proofMode: 'photo',
      description: 'A legible image of solved work, a draft, revision marks, recall output, or assessment artefact.',
      supportedClaimCategoryIds: ['learning_knowledge_gap_diagnosed', 'learning_corrected_solution_completed', 'learning_rubric_application_demonstrated', 'learning_submission_requirements_verified'],
      capturedOutputCategoryIds: ['learning_diagnostic_result_record', 'learning_worked_solution_record', 'learning_draft_section_record', 'learning_revision_record', 'learning_mock_assessment_record', 'learning_submission_readiness_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'learning_explanation_voice',
      proofMode: 'voice',
      description: 'A structured explanation, oral recall, reasoning trace, or teach-back against named material.',
      supportedClaimCategoryIds: ['learning_corrected_solution_completed', 'learning_submission_requirements_verified'],
      capturedOutputCategoryIds: ['learning_worked_solution_record', 'learning_revision_record', 'learning_submission_readiness_record'],
      requiredCaptureCapabilityIds: ['microphone'],
    },
    {
      id: 'learning_hybrid_demonstration',
      proofMode: 'hybrid',
      description: 'A work output paired with explanation where correctness and reasoning both matter.',
      supportedClaimCategoryIds: ['learning_knowledge_gap_diagnosed', 'learning_rubric_application_demonstrated'],
      capturedOutputCategoryIds: ['learning_diagnostic_result_record', 'learning_worked_solution_record', 'learning_draft_section_record', 'learning_mock_assessment_record'],
      requiredCaptureCapabilityIds: ['artifact_capture'],
    },
  ],
  professionalWorkUnitTypes: [
    { id: 'learning_diagnostic_set', description: 'Complete and analyse a representative diagnostic set to locate specific knowledge or skill gaps.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_hybrid_demonstration'], allowedClaimCategoryIds: ['learning_knowledge_gap_diagnosed'], producedOutputCategoryIds: ['learning_diagnostic_result_record'] },
    { id: 'learning_retrieval_block', description: 'Perform closed-book retrieval on named material and correct errors against an authoritative source.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_explanation_voice'], allowedClaimCategoryIds: ['learning_corrected_solution_completed'], producedOutputCategoryIds: ['learning_worked_solution_record'] },
    { id: 'learning_application_set', description: 'Solve a coherent set of problems or cases that require applying the target concept.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_hybrid_demonstration'], allowedClaimCategoryIds: ['learning_rubric_application_demonstrated'], producedOutputCategoryIds: ['learning_worked_solution_record'] },
    { id: 'learning_draft_section', description: 'Produce a complete assessment section tied to named rubric criteria and required output.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_hybrid_demonstration'], allowedClaimCategoryIds: ['learning_rubric_application_demonstrated'], producedOutputCategoryIds: ['learning_draft_section_record'] },
    { id: 'learning_revision_pass', description: 'Revise a draft against feedback or a rubric and record the substantive changes made.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_explanation_voice'], allowedClaimCategoryIds: ['learning_corrected_solution_completed'], producedOutputCategoryIds: ['learning_revision_record'] },
    { id: 'learning_mock_assessment', description: 'Complete a bounded assessment under representative conditions and analyse errors afterward.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_hybrid_demonstration'], allowedClaimCategoryIds: ['learning_rubric_application_demonstrated'], producedOutputCategoryIds: ['learning_mock_assessment_record'] },
    { id: 'learning_submission_check', description: 'Verify the final output against every material rubric, format, citation, and submission requirement.', compatibleEvidenceTypeIds: ['learning_output_photo', 'learning_explanation_voice'], allowedClaimCategoryIds: ['learning_submission_requirements_verified'], producedOutputCategoryIds: ['learning_submission_readiness_record'] },
  ],
  prerequisiteCategories: [
    'assessment_requirements',
    'source_material_access',
    'foundational_knowledge',
    'required_tool_or_format',
    'feedback_or_rubric_access',
  ],
  bottleneckCategories: [
    'specific_knowledge_gap',
    'retrieval_failure',
    'application_failure',
    'drafting_block',
    'rubric_mismatch',
    'revision_quality',
    'submission_risk',
  ],
  progressSignals: [
    'verified_correct_outputs',
    'error_rate_change',
    'rubric_criteria_satisfied',
    'draft_or_revision_completion',
    'assessment_readiness',
  ],
  capabilitySignals: [
    'independent_recall',
    'accurate_application',
    'reasoning_quality',
    'transfer_to_novel_problems',
    'revision_from_feedback',
  ],
  constraintSignals: [
    'assessment_deadline',
    'available_study_time',
    'material_or_tool_access',
    'accommodation_requirement',
    'teacher_or_institution_rule',
  ],
  recoveryReadinessSignals: [
    'cognitive_fatigue',
    'attention_readiness',
    'sleep_related_learning_readiness',
  ],
  hardScalingRules: [
    { id: 'learning_hard_edge_of_mastery', description: 'Target the highest-impact unresolved rubric criterion, knowledge gap, or application level supported by evidence.' },
    { id: 'learning_hard_complete_output', description: 'Require a complete assessment-relevant output, problem set, draft section, or revision pass.' },
    { id: 'learning_hard_representative_conditions', description: 'Increase difficulty through representative recall, application, integration, or assessment conditions, not arbitrary duration.' },
  ],
  mediumScalingRules: [
    { id: 'learning_medium_same_gap', description: 'Keep the same topic, rubric criterion, knowledge gap, or required output as Hard.' },
    { id: 'learning_medium_reduce_scope', description: 'Reduce question count, section length, integration depth, or timed scope while retaining a meaningful result.' },
    { id: 'learning_medium_preserve_retrieval', description: 'Do not replace retrieval or application with passive rereading when the same learning outcome must be demonstrated.' },
  ],
  fixedMissionConditions: [
    { id: 'learning_fixed_assessment_requirement', description: 'An exam, submission, class, supervised task, or institutional requirement fixes the scope, timing, or format.' },
    { id: 'learning_fixed_feedback_deadline', description: 'A teacher or reviewer requires a specific complete output by a fixed deadline.' },
  ],
  clarificationTriggers: [
    { id: 'learning_clarify_assessment', description: 'The assessment, required output, rubric, or success threshold is not known.' },
    { id: 'learning_clarify_gap', description: 'No diagnostic or recent evidence identifies the current knowledge or application gap.' },
    { id: 'learning_clarify_material', description: 'The exact topic, source material, version, or syllabus boundary is ambiguous.' },
    { id: 'learning_clarify_deadline', description: 'The deadline or submission-readiness requirement materially affects the next work unit.' },
  ],
  safetyIntegrityGates: [
    { id: 'learning_gate_academic_integrity', description: 'Reject cheating, impersonation, fabricated citations, or submission of unearned work.' },
    { id: 'learning_gate_assessment_connection', description: 'Require an explicit connection to the assessment, rubric, named material, knowledge gap, or required output.' },
    { id: 'learning_gate_authoritative_correction', description: 'Corrections and standards must use an authoritative source rather than invented requirements.' },
    { id: 'learning_gate_accessibility', description: 'Respect legitimate accommodations and do not interpret them as lower standards of excellence.' },
  ],
  externalPlanRules: [
    { id: 'learning_external_preserve_curriculum', description: 'Preserve valid teacher, institution, tutor, rubric, syllabus, deadline, and assessment requirements with version history.' },
    { id: 'learning_external_label_additions', description: 'Label VISION-added practice separately and never invent the educator or institution strategy.' },
  ],
  forbiddenGenericMissionPatterns: [
    { id: 'learning_forbid_bare_duration', description: 'Study for a duration with no named topic, assessment, rubric criterion, gap, method, or output.' },
    { id: 'learning_forbid_passive_review', description: 'Generic rereading or highlighting when the evidenced bottleneck is recall, application, drafting, or revision.' },
    { id: 'learning_forbid_unrelated_practice', description: 'Practice material selected only because it shares a subject label but does not serve the current syllabus or required output.' },
  ],
  evaluationRuleIds: [
    'learning_assessment_and_rubric_match',
    'learning_specific_gap_leverage',
    'learning_retrieval_or_application_quality',
    'learning_complete_output_value',
    'learning_integrity_and_submission_fit',
  ],
});
