import { defineDomainPack } from './contract.js';

export const moneyDomainPack = defineDomainPack({
  domainId: 'money',
  version: '1.0.0',
  supportedGoalCategories: [
    'earning',
    'saving',
    'debt_reduction',
    'cash_flow',
    'budgeting',
    'investing',
    'risk_management',
    'wealth_protection',
  ],
  milestoneCategories: [
    'income_increase',
    'savings_balance',
    'debt_balance_reduction',
    'positive_cash_flow',
    'budget_stability',
    'investment_plan_execution',
    'protection_coverage',
  ],
  proofCompatibleEvidenceTypes: [
    {
      id: 'money_redacted_record_photo',
      proofMode: 'photo',
      description: 'A privacy-minimised, redacted image of a budget, balance movement, plan, or completed financial action.',
      supportedClaimCategoryIds: ['money_income_action_completed', 'money_savings_action_executed', 'money_principal_payment_executed', 'money_cash_flow_variance_identified', 'money_budget_allocation_decided', 'money_investment_step_executed', 'money_protection_gap_addressed'],
      capturedOutputCategoryIds: ['money_income_outcome_log', 'money_savings_transfer_record', 'money_redacted_payment_confirmation', 'money_cash_flow_review_record', 'money_budget_allocation_record', 'money_investment_policy_record', 'money_risk_protection_record'],
      requiredCaptureCapabilityIds: ['camera'],
    },
    {
      id: 'money_decision_voice',
      proofMode: 'voice',
      description: 'A structured financial decision explanation that avoids requiring invasive account or identity evidence.',
      supportedClaimCategoryIds: ['money_income_action_completed', 'money_cash_flow_variance_identified', 'money_investment_step_executed', 'money_protection_gap_addressed'],
      capturedOutputCategoryIds: ['money_income_outcome_log', 'money_cash_flow_review_record', 'money_investment_policy_record', 'money_risk_protection_record'],
      requiredCaptureCapabilityIds: ['microphone'],
    },
    {
      id: 'money_hybrid_action',
      proofMode: 'hybrid',
      description: 'Redacted action evidence paired with rationale where category fit and execution both require review.',
      supportedClaimCategoryIds: ['money_savings_action_executed', 'money_principal_payment_executed', 'money_budget_allocation_decided'],
      capturedOutputCategoryIds: ['money_savings_transfer_record', 'money_redacted_payment_confirmation', 'money_budget_allocation_record'],
      requiredCaptureCapabilityIds: ['artifact_capture'],
    },
  ],
  professionalWorkUnitTypes: [
    { id: 'money_income_action_block', description: 'Complete an earning action such as a qualified application, offer, pitch, negotiation, or billable delivery with a tracked outcome.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_decision_voice'], allowedClaimCategoryIds: ['money_income_action_completed'], producedOutputCategoryIds: ['money_income_outcome_log'] },
    { id: 'money_savings_transfer_plan', description: 'Execute or establish a savings action tied to a defined target, amount, timing, and cash-flow constraint.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_hybrid_action'], allowedClaimCategoryIds: ['money_savings_action_executed'], producedOutputCategoryIds: ['money_savings_transfer_record'] },
    { id: 'money_debt_repayment_action', description: 'Complete a debt-reduction action based on balance, interest, minimum obligations, and the selected repayment strategy.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_hybrid_action'], allowedClaimCategoryIds: ['money_principal_payment_executed'], producedOutputCategoryIds: ['money_redacted_payment_confirmation'] },
    { id: 'money_cash_flow_review', description: 'Reconcile a bounded period of income and outgoings, identify the material variance, and decide the correction.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_decision_voice'], allowedClaimCategoryIds: ['money_cash_flow_variance_identified'], producedOutputCategoryIds: ['money_cash_flow_review_record'] },
    { id: 'money_budget_allocation', description: 'Build or revise a usable allocation for essential costs, obligations, goals, and a realistic buffer.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_hybrid_action'], allowedClaimCategoryIds: ['money_budget_allocation_decided'], producedOutputCategoryIds: ['money_budget_allocation_record'] },
    { id: 'money_investment_policy_step', description: 'Complete a risk-appropriate investment-planning or execution step after prerequisites and category fit are confirmed.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_decision_voice'], allowedClaimCategoryIds: ['money_investment_step_executed'], producedOutputCategoryIds: ['money_investment_policy_record'] },
    { id: 'money_risk_protection_review', description: 'Review and address a concrete protection gap involving emergency reserves, insurance, fraud, tax, estate, or account security.', compatibleEvidenceTypeIds: ['money_redacted_record_photo', 'money_decision_voice'], allowedClaimCategoryIds: ['money_protection_gap_addressed'], producedOutputCategoryIds: ['money_risk_protection_record'] },
  ],
  prerequisiteCategories: [
    'verified_goal_category',
    'cash_flow_baseline',
    'essential_obligations_known',
    'risk_capacity_and_horizon',
    'qualified_advice_when_required',
  ],
  bottleneckCategories: [
    'insufficient_earning',
    'spending_leak',
    'high_cost_debt',
    'cash_flow_volatility',
    'missing_savings_buffer',
    'risk_mismatch',
    'protection_gap',
  ],
  progressSignals: [
    'net_income_change',
    'savings_balance_change',
    'debt_principal_reduction',
    'cash_flow_surplus',
    'budget_variance_reduction',
    'protection_gap_closed',
  ],
  capabilitySignals: [
    'accurate_financial_tracking',
    'consistent_plan_execution',
    'risk_appropriate_decision_making',
    'negotiation_or_earning_execution',
    'fraud_and_fee_awareness',
  ],
  constraintSignals: [
    'essential_cost_floor',
    'income_volatility',
    'debt_terms',
    'liquidity_need',
    'legal_tax_or_regulatory_context',
    'risk_tolerance_and_capacity',
  ],
  recoveryReadinessSignals: [
    'financial_stress_load',
    'decision_readiness',
    'capacity_for_administration',
  ],
  hardScalingRules: [
    { id: 'money_hard_category_leverage', description: 'Choose the highest-impact action inside the actual earning, saving, debt, cash-flow, investing, or protection category.' },
    { id: 'money_hard_material_outcome', description: 'Increase the material amount, negotiation consequence, analysis completeness, or protection value only within evidenced capacity.' },
    { id: 'money_hard_risk_preserved', description: 'Greater challenge must never mean greater unexamined leverage, concentration, fraud exposure, or inability to meet essential obligations.' },
  ],
  mediumScalingRules: [
    { id: 'money_medium_same_financial_outcome', description: 'Keep the same financial category, obligation, account decision, or outcome as Hard.' },
    { id: 'money_medium_reduce_scope', description: 'Reduce the number of accounts, transaction period, outreach batch, or nonessential analysis while preserving a usable decision or action.' },
    { id: 'money_medium_no_category_substitution', description: 'Do not replace debt, savings, earning, cash-flow, or protection work with unrelated investing content.' },
  ],
  fixedMissionConditions: [
    { id: 'money_fixed_legal_obligation', description: 'A tax, debt, payroll, court, regulatory, benefits, or contractual obligation has a fixed requirement or deadline.' },
    { id: 'money_fixed_transaction_deadline', description: 'A settlement, maturity, renewal, payment, or application deadline cannot be rescaled without changing the obligation.' },
  ],
  clarificationTriggers: [
    { id: 'money_clarify_goal_category', description: 'It is unclear whether the goal concerns earning, saving, debt, cash flow, budgeting, investing, risk, or protection.' },
    { id: 'money_clarify_constraints', description: 'Essential obligations, liquidity needs, debt terms, or financial capacity are missing.' },
    { id: 'money_clarify_risk', description: 'An investing or protection action lacks a risk horizon, capacity, or relevant professional context.' },
    { id: 'money_clarify_authority', description: 'The task may require licensed legal, tax, credit, insurance, or financial advice.' },
  ],
  safetyIntegrityGates: [
    { id: 'money_gate_no_high_risk_leverage', description: 'Reject gambling, reckless leverage, predatory products, illegal evasion, fraud, or promises of guaranteed returns.' },
    { id: 'money_gate_category_match', description: 'Require the mission to match the actual financial goal category and current bottleneck.' },
    { id: 'money_gate_minimise_private_evidence', description: 'Never require invasive statements, full account numbers, identity documents, or unnecessary financial records.' },
    { id: 'money_gate_licensed_boundary', description: 'Do not fabricate or impersonate licensed legal, tax, credit, insurance, or investment advice.' },
  ],
  externalPlanRules: [
    { id: 'money_external_preserve_obligations', description: 'Preserve valid accountant, adviser, court, lender, employer, benefits, or regulatory requirements and deadlines.' },
    { id: 'money_external_label_additions', description: 'Label VISION-added educational guidance separately and never invent licensed advice or alter an active obligation silently.' },
  ],
  forbiddenGenericMissionPatterns: [
    { id: 'money_forbid_forced_investing', description: 'Investing advice inserted into an earning, savings, debt-reduction, cash-flow, budgeting, or protection goal.' },
    { id: 'money_forbid_context_free_budget_cut', description: 'Generic expense cutting without regard to essential obligations, actual cash-flow data, or the goal category.' },
    { id: 'money_forbid_vague_money_research', description: 'Research money or learn finance with no decision, account, obligation, risk, or measurable output.' },
  ],
  evaluationRuleIds: [
    'money_goal_category_correctness',
    'money_material_financial_progress',
    'money_cash_flow_and_obligation_fit',
    'money_risk_and_protection_integrity',
    'money_privacy_minimisation',
  ],
});
